apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.flask.name }}
  labels:
    app: {{ .Values.flask.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.flask.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.flask.name }}
    spec:
      containers:
      - name: {{ .Values.flask.name }}
        image: {{ .Values.flask.image }}
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
      imagePullSecrets:
      - name: regcred2
